### ISSUE TITLE
Missing image in CAW blog post

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/website#11]
The CAW logo is not accessible any more in the CAW blog post. 

See https://www.nextflow.io/blog/2017/caw-and-singularity.html

Document 

https://github.com/nextflow-io/website/blob/master/content/blog/2017/caw-and-singularity.md

**Comment by pditommaso** [comment]
@MaxUlysse Is there a replacement for the following link? 

```
https://raw.githubusercontent.com/SciLifeLab/CAW/master/doc/images/CAW_logo.png
```

**Comment by MaxUlysse** [comment]
@pditommaso 
Yes, sorry, it's : 
`https://raw.githubusercontent.com/SciLifeLab/CAW/master/docs/images/CAW_logo.png`

**Comment by pditommaso** [comment]
Thanks!
