### ISSUE TITLE
CAW link the blog post does not work any more

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/website#12]
The first link in [CAW](https://www.nextflow.io/blog/2017/caw-and-singularity.html) blog post is broken. @MaxUlysse is there an alternative link?

**Comment by MaxUlysse** [comment]
There should have been a redirection.

It is now fixed thanks to @ewels

**Comment by ewels** [comment]
I fixed it, but then I broke it again sorry. It should be double-fixed soon...
