### ISSUE TITLE
In the FAQ example there is an "every" which should not be there

### ISSUE THREAD

**Issue by BioPsyk** [nextflow-io/website#18]
https://github.com/nextflow-io/website/blob/852b8bad17bf093d54dbdb65ff0185869048a211/assets/docs/edge/faq.html#L367

In the FAQ example there is an "every" which should not be there.

It is likely obvious for people knowing groovy, otherwise you have to trust the docs, and then it can take many hours to realise that all experienced problems are due to the typo :)

**Comment by pditommaso** [comment]
Fixed in the main repo https://github.com/nextflow-io/nextflow/commit/fd2df592f394190c78cac05500df9ff11e6c8821. Thanks for reporting.
