### ISSUE TITLE
New article, or just update the dates to 2024?

### ISSUE THREAD

**Issue by Shaun-Regenbaum** [nextflow-io/website#187]
For the Quick Start to [learning nextflow](https://nextflow.io/blog/2023/learn-nextflow-in-2023.html), is there a need to write a new article or can we just update the dates of the existing article? 
<img width="796" alt="image" src="https://github.com/nextflow-io/website/assets/12636260/d797f7ee-b4f4-4a61-835e-67148959b265">

I personally think the existing article is great, but for a starting document for beginners, I think its important to change the year to 2024 so newcomers understand Nextflow is still active when exploring the main website.

**Comment by mribeirodantas** [comment]
Hey @Shaun-Regenbaum. We're working on replacing this soon 😉.

Thanks for the feedback.
