### ISSUE TITLE
Update nextflow patterns

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/website#41]
Patterns documentation needs to be updated to DSL2 syntax 

https://github.com/nextflow-io/patterns

**Comment by bentsherman** [comment]
I have a PR ready for this one as well. If you add me as a collaborator to the patterns repo I will push it when I get back on Wednesday.

**Comment by bentsherman** [comment]
Closing this issue in favor of the corresponding issue https://github.com/nextflow-io/patterns/issues/23
