### ISSUE TITLE
Permalink Slack invite URL

### ISSUE THREAD

**Issue by ewels** [nextflow-io/website#49]
As mentioned [here](https://github.com/nextflow-io/nextflow/pull/2917#issuecomment-1145379926), it would be nice to have a permalink for the Slack invite, which expires.

There are a few ways to do redirects, but assuming that the website is running with Apache (@pditommaso is it?), the cleanest may be with a `.htaccess` file. I've not used Jbake before, but I _think_ we can put a `.htaccess` into [`assets`](https://github.com/nextflow-io/website/tree/036da33f248a70276476b86d0f87ce7e1332639c/assets) _(NB: [not `content`](https://bytemeta.vip/repo/jbake-org/jbake/issues/688))_ and it should be copied into the root. We can then rewrite the Slack join URL:

```apache
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /

    # Slack invite permalink
    RewriteRule ^/?slack-invite/?$ https://join.slack.com/t/nextflow/shared_invite/zt-11iwlxtw5-R6SNBpVksOJAx5sPOXNrZg [R=301,L]
</IfModule>
```

Then we need to update the website in at least a couple of places to use https://nextflow.io/slack-invite

https://github.com/nextflow-io/website/blob/f8ad690450fbc1dc0944c8db71be93ffd517c69c/templates/menu.ftl#L47

https://github.com/nextflow-io/website/blob/036da33f248a70276476b86d0f87ce7e1332639c/content/blog/2022/nextflow-is-moving-to-slack.md?plain=1#L30

**Comment by pditommaso** [comment]
> There are a few ways to do redirects, but assuming that the website is running with Apache (@pditommaso is it?)

Nope! it's a static website on S3. Not aware it's possible to handle redirect at that level, think it should be done with a redirect page.

**Comment by ewels** [comment]
Ah ok. Looks like it is, through the s3 interface: https://docs.aws.amazon.com/AmazonS3/latest/userguide/how-to-page-redirect.html#advanced-conditional-redirects

So maybe something like this?

```json
[
    {
        "Condition": {
            "KeyPrefixEquals": "slack-invite"
        },
        "Redirect": {
            "HostName": "join.slack.com",
            "Protocol": "https",
            "ReplaceKeyWith": "t/nextflow/shared_invite/zt-11iwlxtw5-R6SNBpVksOJAx5sPOXNrZg"
        }
    }
]
```

A redirect page is fine as well though 👍🏻  (just my paranoia about disliking doing it client-side instead of server-side, I agree that it should be functionally identical).
