### ISSUE TITLE
DSL2 docs conversion

### ISSUE THREAD

**Issue by ewels** [nextflow-io/website#53]
There is a lot of Nextflow documentation across multiple locations that require updating to DSL2.

This issue is to provide a central location to track this effort. Each source should have its own issue / PR to track specifics.

- [x] Nextflow website: reference docs
    - https://github.com/nextflow-io/nextflow/issues/2742
    - https://github.com/nextflow-io/nextflow/pull/2816
- [x] Nextflow website: examples
    - https://github.com/nextflow-io/website/issues/40 
    - https://github.com/nextflow-io/website/pull/44
- [x] Nextflow patterns
    - https://github.com/nextflow-io/patterns/issues/23
    - https://github.com/nextflow-io/patterns/pull/26
- [x] Seqera training material
    - https://github.com/seqeralabs/nf-training-public/pull/82

There's also all of the nf-core stuff, but let's keep this pure Nextflow community for now.

Please add / comment about anything I missed!

**Comment by bentsherman** [comment]
All done!

**Comment by ewels** [comment]
![](https://c.tenor.com/aps3ea5zt1EAAAAC/viva-la-revolution.gif)
