### ISSUE TITLE
Add usage example to ext option

### ISSUE THREAD

**Issue by jgrzebyta** [nextflow-io/website#6]
I will add usage example for option `ext` directive.

**Comment by pditommaso** [comment]
Thanks for the initiative but the documentation is located in the main NF repository 

https://github.com/nextflow-io/nextflow/blob/master/docs/process.rst#ext

**Comment by jgrzebyta** [comment]
OK. Thanks

**Comment by jgrzebyta** [comment]
Wrong project.
